# Generated by Django 4.2.1 on 2023-05-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_username_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('level', models.IntegerField()),
                ('status', models.BooleanField()),
                ('date', models.DateField()),
                ('gpa', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
